name: marionette_mcp_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/marionette_mcp
  - packages/marionette_flutter
  - packages/marionette_logging
  - packages/marionette_logger
  - example
  - tool
